# Generated by Django 6.0.5 on 2026-07-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_ai_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='ai_analysis',
            field=models.TextField(blank=True, default=dict),
        ),
    ]
