CAREERS = [
    ("AI Engineer", "🤖", "Build AI and Machine Learning applications."),
    ("Data Scientist", "🧠", "Analyze data and build predictive models."),
    ("Data Analyst", "📊", "Extract insights from business data."),
    ("Web Developer", "🌐", "Build websites and web applications."),
    ("Frontend Developer", "🎨", "Develop modern user interfaces."),
    ("Backend Developer", "⚙️", "Build APIs and server-side applications."),
    ("Full Stack Developer", "💻", "Develop both frontend and backend."),
    ("Flutter Developer", "📱", "Build cross-platform mobile apps."),
    ("Android Developer", "🤖", "Develop Android applications."),
    ("iOS Developer", "🍎", "Develop iPhone and iPad apps."),
    ("Cloud Engineer", "☁️", "Manage cloud infrastructure."),
    ("DevOps Engineer", "🚀", "Automate deployment and CI/CD."),
    ("Cyber Security Engineer", "🛡️", "Protect systems from cyber attacks."),
    ("Ethical Hacker", "🔐", "Find and fix security vulnerabilities."),
    ("Network Engineer", "🌍", "Manage computer networks."),
    ("Software Engineer", "💼", "Design and build software systems."),
    ("QA Engineer", "✅", "Test software quality."),
    ("Game Developer", "🎮", "Develop video games."),
    ("Blockchain Developer", "⛓️", "Build blockchain applications."),
    ("UI/UX Designer", "🎨", "Design user experiences."),
    ("Product Manager", "📦", "Lead product development."),
    ("Prompt Engineer", "✨", "Create and optimize AI prompts."),
]