# Generated by Django 6.0.5 on 2026-07-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='career',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='career',
            name='icon',
            field=models.CharField(default='💼', max_length=10),
        ),
        migrations.AddField(
            model_name='career',
            name='popular',
            field=models.BooleanField(default=True),
        ),
    ]
