# Generated by Django 6.0.5 on 2026-07-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_careercatalog_career_description_career_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='description',
        ),
        migrations.RemoveField(
            model_name='career',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='career',
            name='popular',
        ),
        migrations.AddField(
            model_name='careercatalog',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='careercatalog',
            name='icon',
            field=models.CharField(default='💼', max_length=10),
        ),
        migrations.AddField(
            model_name='careercatalog',
            name='popular',
            field=models.BooleanField(default=True),
        ),
    ]
