# Generated by Django 6.0.5 on 2026-07-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_career_description_remove_career_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careercatalog',
            name='roadmap',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='careercatalog',
            name='description',
            field=models.CharField(default='', max_length=120),
        ),
    ]
