# Generated by Django 6.0.5 on 2026-07-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_careercatalog_roadmap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careercatalog',
            name='roadmap',
        ),
        migrations.AlterField(
            model_name='careercatalog',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
