# Generated by Django 6.0.5 on 2026-08-08 18:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='profile_pictures/default', max_length=255, verbose_name='profile_picture'),
        ),
    ]
