# Generated by Django 6.0.5 on 2026-07-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
    ]
